Traceback (most recent call last):
  File "main.py", line 434, in <module>
    main()
  File "main.py", line 206, in main
    exchange_.MakeOrderExchange()
  File "/home/kevin/Programing/python/World_RTS_2/actions.py", line 224, in MakeOrderExchange
    self.DeleteAction()
  File "/home/kevin/Programing/python/World_RTS_2/actions.py", line 59, in DeleteAction
    self.acter.action.remove(self) #remove self from acter action list
ValueError: list.remove(x): x not in list


